services:
  nginx:
    build:
      context: ./nginx/
    volumes:
      - ./front-end:/var/www/app
    ports:
      - "443:443"
      - "8010:80"
  api:
    build:
      context: ./api/
    env_file:
      - .env-api-prod
    volumes:
      - ./api:/app/api
      - sqlite-db:/app/data/
    ports:
      - "8002:5000"
    command: gunicorn 'api.server:create_app()'

  client:
    build:
      context: ./client/
    volumes:
      - ./front-end:/app/dist
    command: npm run build
volumes:
  sqlite-db:

