version: '3.8'

services:
  # Development service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./localhost.pem:/app/localhost.pem:ro
      - ./localhost-key.pem:/app/localhost-key.pem:ro
    environment:
      - NODE_ENV=development

